import os
from extrapolating.update_if_matched import update_if_matched, MatchType

def guess_scans(res_dict, commit = True):
    """
    Attempts to generate scan file names based on the path of the corresponding string table, and vice versa.

    :param res_dict: A dict of integer hashes to string filenames. Non-matching filenames should be suffixed with "!!".
    :param commit: Whether generated matches should be automatically added to the resource dictionary. Defaults to False
    :return: Number of newly-added filename matches, as an int.
    """
    print("Checking scans...")
    matched = 0

    scan_folders = { # todo: Lookup by MREA name
        '$/ScannableObjects/Inventory',
        '$/ScannableObjects/Cliffs/00_cliff_generator',
        '$/ScannableObjects/Cliffs/00_cliff_generator_08_temple',
        '$/ScannableObjects/Cliffs/00_cliff_generator_connect',
        '$/ScannableObjects/Cliffs/00_elev_cliff_sand_d',
        '$/ScannableObjects/Cliffs/00_elev_cliff_swamp_f',
        '$/ScannableObjects/Cliffs/00_elev_cliff_temple_c',
        '$/ScannableObjects/Cliffs/00_pickup_cliff_a',
        '$/ScannableObjects/Cliffs/00_pickup_cliff_c',
        '$/ScannableObjects/Cliffs/00_save_cliff_a',
        '$/ScannableObjects/Cliffs/00_save_cliff_b',
        '$/ScannableObjects/Cliffs/01_cliff_entrance',
        '$/ScannableObjects/Cliffs/02_cliff_reactorcore',
        '$/ScannableObjects/Cliffs/03_cliff_chicane',
        '$/ScannableObjects/Cliffs/04_cliff_contraption',
        '$/ScannableObjects/Cliffs/05_cliff_engine',
        '$/ScannableObjects/Cliffs/06_cliff_spiderballguardian',
        '$/ScannableObjects/Cliffs/07_cliff_gyro',
        '$/ScannableObjects/Cliffs/08_cliff_ringtowers',
        '$/ScannableObjects/Cliffs/09_cliff_temple',
        '$/ScannableObjects/Cliffs/0a_cliff_hall',
        '$/ScannableObjects/Cliffs/0b_cliff_hall',
        '$/ScannableObjects/Cliffs/0c_cliff_hall',
        '$/ScannableObjects/Cliffs/0d_cliff_hall',
        '$/ScannableObjects/Cliffs/0e_cliff_hall',
        '$/ScannableObjects/Cliffs/0f_cliff_hall',
        '$/ScannableObjects/Cliffs/0g_cliff_hall',
        '$/ScannableObjects/Cliffs/0h_cliff_hall',
        '$/ScannableObjects/Cliffs/0i_cliff_hall',
        '$/ScannableObjects/Cliffs/0j_cliff_hall_bottom',
        '$/ScannableObjects/Cliffs/0j_cliff_hall_loop',
        '$/ScannableObjects/Cliffs/0k_cliff_hall',
        '$/ScannableObjects/Cliffs/0l_cliff_hall',
        '$/ScannableObjects/Cliffs/0m_cliff_hall',
        '$/ScannableObjects/Cliffs/0n_cliff_hall',
        '$/ScannableObjects/Cliffs/0o_cliff_hall',
        '$/ScannableObjects/Cliffs/0p_cliff_hall',
        '$/ScannableObjects/Cliffs/0q_cliff_hall',
        '$/ScannableObjects/Cliffs/10_cliff_rooftop',
        '$/ScannableObjects/Dark Cliffs/00_cliff_generator_connect_dark',
        '$/ScannableObjects/Dark Cliffs/00_cliff_generator_dark',
        '$/ScannableObjects/Dark Cliffs/00_pickup_cliff_a_dark',
        '$/ScannableObjects/Dark Cliffs/00_pickup_cliff_c_dark',
        '$/ScannableObjects/Dark Cliffs/00_save_cliff_a_dark',
        '$/ScannableObjects/Dark Cliffs/00_save_cliff_b_dark',
        '$/ScannableObjects/Dark Cliffs/01_cliff_entrance_dark',
        '$/ScannableObjects/Dark Cliffs/02_cliff_reactorcore_dark',
        '$/ScannableObjects/Dark Cliffs/03_cliff_chicane_dark',
        '$/ScannableObjects/Dark Cliffs/04_cliff_contraption_dark',
        '$/ScannableObjects/Dark Cliffs/05_cliff_engine_dark',
        '$/ScannableObjects/Dark Cliffs/06_cliff_spiderballguardian_dark',
        '$/ScannableObjects/Dark Cliffs/07_cliff_gyro_dark',
        '$/ScannableObjects/Dark Cliffs/08_cliff_ringtowers_dark',
        '$/ScannableObjects/Dark Cliffs/09_cliff_temple_dark',
        '$/ScannableObjects/Dark Cliffs/0b_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/0c_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/0d_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/0e_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/0f_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/0g_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/0i_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/0j_cliff_hall_bottom_dark',
        '$/ScannableObjects/Dark Cliffs/0l_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/0m_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/0n_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/0o_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/0q_cliff_hall_dark',
        '$/ScannableObjects/Dark Cliffs/10_cliff_rooftop_dark',
        '$/ScannableObjects/Dark Sandlands/00_pickup_sand_b_dark',
        '$/ScannableObjects/Dark Sandlands/00_pickup_sand_c_dark',
        '$/ScannableObjects/Dark Sandlands/00_pickup_sand_d_dark',
        '$/ScannableObjects/Dark Sandlands/00_sand_generator_connect_dark',
        '$/ScannableObjects/Dark Sandlands/00_sand_generator_dark',
        '$/ScannableObjects/Dark Sandlands/00_save_sand_a_dark',
        '$/ScannableObjects/Dark Sandlands/00_save_sand_c_dark',
        '$/ScannableObjects/Dark Sandlands/01_sand_entrance_dark',
        '$/ScannableObjects/Dark Sandlands/02_sand_sandfalls_dark',
        '$/ScannableObjects/Dark Sandlands/03_sand_temple_dark',
        '$/ScannableObjects/Dark Sandlands/04_sand_mining_dark',
        '$/ScannableObjects/Dark Sandlands/05_sand_portalpuzzle_dark',
        '$/ScannableObjects/Dark Sandlands/06_sand_alamofront_dark',
        '$/ScannableObjects/Dark Sandlands/07_sand_alamoportal_dark',
        '$/ScannableObjects/Dark Sandlands/08_sand_casualpirates_dark',
        '$/ScannableObjects/Dark Sandlands/09_sand_testtubepuzzle_dark',
        '$/ScannableObjects/Dark Sandlands/0a_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0c_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0d_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0e_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0f_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0g_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0h_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0i_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0j_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0k_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0l_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0m_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0n_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0o_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/0q_sand_hall_dark',
        '$/ScannableObjects/Dark Sandlands/10_sand_alamostorage_dark',
        '$/ScannableObjects/Dark Swamplands/00_elev_swamp_sand_e_dark',
        '$/ScannableObjects/Dark Swamplands/00_map_swamp_dark',
        '$/ScannableObjects/Dark Swamplands/00_pickup_swamp_a_dark',
        '$/ScannableObjects/Dark Swamplands/00_pickup_swamp_b_dark',
        '$/ScannableObjects/Dark Swamplands/00_save_swamp_b_dark',
        '$/ScannableObjects/Dark Swamplands/00_swamp_genconnect_dark',
        '$/ScannableObjects/Dark Swamplands/00_swamp_generator_dark',
        '$/ScannableObjects/Dark Swamplands/01_swamp_entrance_dark',
        '$/ScannableObjects/Dark Swamplands/02_swamp_greatbridge_dark',
        '$/ScannableObjects/Dark Swamplands/03_swamp_forgottenbridge_dark',
        '$/ScannableObjects/Dark Swamplands/04_swamp_temple_dark',
        '$/ScannableObjects/Dark Swamplands/05_swamp_timber!_dark',
        '$/ScannableObjects/Dark Swamplands/06_swamp_boostballguardian_dark',
        '$/ScannableObjects/Dark Swamplands/07_swamp_shaft_dark',
        '$/ScannableObjects/Dark Swamplands/08_swamp_grappleguardian_dark',
        '$/ScannableObjects/Dark Swamplands/09_swamp_catacombs_dark',
        '$/ScannableObjects/Dark Swamplands/0c_swamp_hall_dark',
        '$/ScannableObjects/Dark Swamplands/0d_swamp_hall_dark',
        '$/ScannableObjects/Dark Swamplands/0e_swamp_hall_dark',
        '$/ScannableObjects/Dark Swamplands/0f_swamp_hall_dark',
        '$/ScannableObjects/Dark Swamplands/0h_swamp_hall_dark',
        '$/ScannableObjects/Dark Swamplands/0i_swamp_hall_dark',
        '$/ScannableObjects/Dark Swamplands/0j_swamp_hall_dark',
        '$/ScannableObjects/Dark Swamplands/0l_swamphall_dark',
        '$/ScannableObjects/Dark Swamplands/0n_swamp_hall_dark',
        '$/ScannableObjects/Dark Swamplands/0o_swamp_hall_dark',
        '$/ScannableObjects/Dark Swamplands/0q_swamp_hall_dark',
        '$/ScannableObjects/Dark Swamplands/10_swamp_hiddenhalfpipe_dark',
        '$/ScannableObjects/Dark Swamplands/11_swamp_bloggtank_dark',
        '$/ScannableObjects/Dark Swamplands/ok_swamp_hall_dark',
        '$/ScannableObjects/Light Temple/00_elev_temple_cliff_c',
        '$/ScannableObjects/Light Temple/00_elev_temple_sand_a',
        '$/ScannableObjects/Light Temple/00_elev_temple_swamp_b',
        '$/ScannableObjects/Light Temple/00_pickup_temple_a',
        '$/ScannableObjects/Light Temple/00_pickup_temple_b',
        '$/ScannableObjects/Light Temple/00_save_hive04',
        '$/ScannableObjects/Light Temple/00_scandummy',
        '$/ScannableObjects/Light Temple/01_Temple_LandingSite',
        '$/ScannableObjects/Light Temple/01_temple_hive_01',
        '$/ScannableObjects/Light Temple/01_temple_hive_02',
        '$/ScannableObjects/Light Temple/01_temple_hive_03',
        '$/ScannableObjects/Light Temple/01_temple_hive_04',
        '$/ScannableObjects/Light Temple/02_temple_exploration',
        '$/ScannableObjects/Light Temple/03_temple_combattraining',
        '$/ScannableObjects/Light Temple/04_temple_unknownenemies',
        '$/ScannableObjects/Light Temple/05_temple_federationsite',
        '$/ScannableObjects/Light Temple/06_temple_sacredpath',
        '$/ScannableObjects/Light Temple/07_temple_mothlordsanctuary',
        '$/ScannableObjects/Light Temple/08_temple_sungenerator',
        '$/ScannableObjects/Light Temple/09_temple_thirdleg',
        '$/ScannableObjects/Light Temple/0a_temple_hall',
        '$/ScannableObjects/Light Temple/0b_temple_hall',
        '$/ScannableObjects/Light Temple/0c_temple_hall',
        '$/ScannableObjects/Light Temple/0d_temple_hall',
        '$/ScannableObjects/Light Temple/0e_temple_hall',
        '$/ScannableObjects/Light Temple/0e_temple_hive_hall',
        '$/ScannableObjects/Light Temple/0f_temple_hall',
        '$/ScannableObjects/Light Temple/0f_temple_hive_hall',
        '$/ScannableObjects/Light Temple/0g_temple_hall',
        '$/ScannableObjects/Light Temple/0h_temple_hall',
        '$/ScannableObjects/Light Temple/0i_temple_hall',
        '$/ScannableObjects/Light Temple/0j_temple_hall',
        '$/ScannableObjects/Light Temple/0j_temple_hall_top',
        '$/ScannableObjects/Light Temple/0k_temple_hall',
        '$/ScannableObjects/Light Temple/0l_temple_hall',
        '$/ScannableObjects/Light Temple/0m_temple_hall',
        '$/ScannableObjects/Light Temple/0n_temple_hall',
        '$/ScannableObjects/Light Temple/0o_temple_hall',
        '$/ScannableObjects/Light Temple/0p_temple_hall',
        '$/ScannableObjects/Light Temple/0q_temple_hall',
        '$/ScannableObjects/Light Temple/0r_temple_hall',
        '$/ScannableObjects/Light Temple/0s_temple_hall',
        '$/ScannableObjects/Light Temple/0t_temple_hall',
        '$/ScannableObjects/Light Temple/0u_temple_hall',
        '$/ScannableObjects/Light Temple/10_temple_pathofeyes',
        '$/ScannableObjects/Light Temple/11_temple_grandpuzzle',
        '$/ScannableObjects/Light Temple/12_temple_finalgate',
        '$/ScannableObjects/Light Temple/OF_Temple_hall_top',
        '$/ScannableObjects/Light Temple/game_end_part1',
        '$/ScannableObjects/Light Temple/game_end_part2',
        '$/ScannableObjects/Light Temple/game_end_part3',
        '$/ScannableObjects/Light Temple/game_end_part4',
        '$/ScannableObjects/Light Temple/game_end_part5',
        '$/ScannableObjects/Light Temple/om_temple_hall_top',
        '$/ScannableObjects/Sandlands/00_Elev_Sand_Temple_A',
        '$/ScannableObjects/Sandlands/00_elev_sand_cliff_d',
        '$/ScannableObjects/Sandlands/00_elev_sand_swamp_e',
        '$/ScannableObjects/Sandlands/00_mapstation_sand',
        '$/ScannableObjects/Sandlands/00_pickup_sand_a',
        '$/ScannableObjects/Sandlands/00_pickup_sand_b',
        '$/ScannableObjects/Sandlands/00_pickup_sand_c',
        '$/ScannableObjects/Sandlands/00_pickup_sand_d',
        '$/ScannableObjects/Sandlands/00_sand_generator',
        '$/ScannableObjects/Sandlands/00_sand_generator_08_temple',
        '$/ScannableObjects/Sandlands/00_sand_generator_connect',
        '$/ScannableObjects/Sandlands/00_save_sand_a',
        '$/ScannableObjects/Sandlands/00_save_sand_c',
        '$/ScannableObjects/Sandlands/01_sand_entrance',
        '$/ScannableObjects/Sandlands/02_sand_sandfalls',
        '$/ScannableObjects/Sandlands/03_sand_temple',
        '$/ScannableObjects/Sandlands/04_sand_mining',
        '$/ScannableObjects/Sandlands/05_sand_portalpuzzle',
        '$/ScannableObjects/Sandlands/06_sand_alamofront',
        '$/ScannableObjects/Sandlands/07_sand_alamoportal',
        '$/ScannableObjects/Sandlands/08_sand_casualpirates',
        '$/ScannableObjects/Sandlands/09_sand_testtubepuzzle',
        '$/ScannableObjects/Sandlands/0a_sand_hall',
        '$/ScannableObjects/Sandlands/0b_sand_hall',
        '$/ScannableObjects/Sandlands/0c_sand_hall',
        '$/ScannableObjects/Sandlands/0d_sand_hall',
        '$/ScannableObjects/Sandlands/0e_sand_hall',
        '$/ScannableObjects/Sandlands/0f_sand_hall',
        '$/ScannableObjects/Sandlands/0g_sand_hall',
        '$/ScannableObjects/Sandlands/0h_sand_hall',
        '$/ScannableObjects/Sandlands/0i_sand_hall',
        '$/ScannableObjects/Sandlands/0j_sand_hall',
        '$/ScannableObjects/Sandlands/0k_sand_hall',
        '$/ScannableObjects/Sandlands/0l_sand_hall',
        '$/ScannableObjects/Sandlands/0m_sand_hall',
        '$/ScannableObjects/Sandlands/0n_sand_hall',
        '$/ScannableObjects/Sandlands/0o_sand_hall',
        '$/ScannableObjects/Sandlands/0p_sand_hall',
        '$/ScannableObjects/Sandlands/0q_sand_hall',
        '$/ScannableObjects/Sandlands/10_sand_alamostorage',
        '$/ScannableObjects/Sky Temple/00_pickup_temple_a_dark',
        '$/ScannableObjects/Sky Temple/01_temple_hive03_dark',
        '$/ScannableObjects/Sky Temple/01_temple_landingsite_dark',
        '$/ScannableObjects/Sky Temple/02_temple_exploration_dark',
        '$/ScannableObjects/Sky Temple/03_temple_combattraining_dark',
        '$/ScannableObjects/Sky Temple/04_temple_unknownenemies_dark',
        '$/ScannableObjects/Sky Temple/05_temple_federationsite_dark',
        '$/ScannableObjects/Sky Temple/06_temple_sacredpath_dark',
        '$/ScannableObjects/Sky Temple/07_temple_mothlordsanctuary_dark',
        '$/ScannableObjects/Sky Temple/08_temple_sungenerator_dark',
        '$/ScannableObjects/Sky Temple/09_temple_thirdleg_dark',
        '$/ScannableObjects/Sky Temple/0b_temple_hall_dark',
        '$/ScannableObjects/Sky Temple/0d_temple_hall_dark',
        '$/ScannableObjects/Sky Temple/0e_temple_hall_dark',
        '$/ScannableObjects/Sky Temple/0h_temple_hall_dark',
        '$/ScannableObjects/Sky Temple/0n_temple_hall_dark',
        '$/ScannableObjects/Sky Temple/0q_temple_hall_dark',
        '$/ScannableObjects/Sky Temple/0t_temple_hall_dark',
        '$/ScannableObjects/Sky Temple/10_temple_pathofeyes_dark',
        '$/ScannableObjects/Sky Temple/11_temple_grandpuzzle_dark',
        '$/ScannableObjects/Sky Temple/12_temple_finalgate_dark',
        '$/ScannableObjects/Swamplands/00_Elev_Swamp_Temple_B',
        '$/ScannableObjects/Swamplands/00_elev_swamp_cliff_f',
        '$/ScannableObjects/Swamplands/00_elev_swamp_sand_e',
        '$/ScannableObjects/Swamplands/00_map_swamp',
        '$/ScannableObjects/Swamplands/00_pickup_swamp_a',
        '$/ScannableObjects/Swamplands/00_pickup_swamp_b',
        '$/ScannableObjects/Swamplands/00_pickup_swamp_c',
        '$/ScannableObjects/Swamplands/00_save_swamp_b',
        '$/ScannableObjects/Swamplands/00_swamp_genconnect',
        '$/ScannableObjects/Swamplands/00_swamp_generator',
        '$/ScannableObjects/Swamplands/00_swamp_generator_08_temple',
        '$/ScannableObjects/Swamplands/01_swamp_entrance',
        '$/ScannableObjects/Swamplands/02_swamp_greatbridge',
        '$/ScannableObjects/Swamplands/03_swamp_forgottenbridge',
        '$/ScannableObjects/Swamplands/04_swamp_temple',
        '$/ScannableObjects/Swamplands/05_swamp_timber!',
        '$/ScannableObjects/Swamplands/06_swamp_boostballguardian',
        '$/ScannableObjects/Swamplands/07_swamp_shaft',
        '$/ScannableObjects/Swamplands/08_swamp_grappleguardian',
        '$/ScannableObjects/Swamplands/09_swamp_catacombs',
        '$/ScannableObjects/Swamplands/0a_swamp_hall',
        '$/ScannableObjects/Swamplands/0b_swamp_hall',
        '$/ScannableObjects/Swamplands/0c_swamp_hall',
        '$/ScannableObjects/Swamplands/0d_swamp_hall',
        '$/ScannableObjects/Swamplands/0e_swamp_hall',
        '$/ScannableObjects/Swamplands/0f_swamp_hall',
        '$/ScannableObjects/Swamplands/0g_swamp_hall',
        '$/ScannableObjects/Swamplands/0h_swamp_hall',
        '$/ScannableObjects/Swamplands/0i_swamp_hall',
        '$/ScannableObjects/Swamplands/0j_swamp_hall',
        '$/ScannableObjects/Swamplands/0l_swamphall',
        '$/ScannableObjects/Swamplands/0m_swamp_hall',
        '$/ScannableObjects/Swamplands/0n_swamp_hall',
        '$/ScannableObjects/Swamplands/0o_swamp_hall',
        '$/ScannableObjects/Swamplands/0p_swamp_hall',
        '$/ScannableObjects/Swamplands/0q_swamp_hall',
        '$/ScannableObjects/Swamplands/0r_swamp_hall',
        '$/ScannableObjects/Swamplands/10_swamp_hiddenhalfpipe',
        '$/ScannableObjects/Swamplands/11_swamp_bloggtank',
        '$/ScannableObjects/Swamplands/ok_swamp_hall',
    }
    scan_names = {'01 hive3 dead grenchler 1.scan', '01_hive2 dead grenchler 1.scan',  '01_hive1 dead grenchler 1.scan', 'Bacteria.scan'}
    strg_folders = set()
    strg_names = {'Luminoth Crate.strg', '07_Temple Dead Cocoon.strg', 'Large Crate.strg', 'Dark GF Trooper.strg' }

    for key in res_dict:
        if res_dict[key].endswith('strg') and 'scan_data' in res_dict[key].lower():
            strg_folder, strg = os.path.split(res_dict[key])
            scan = strg[:-5] + '.scan'
            scan_names.add(scan)
            strg_folders.add(strg_folder)
        elif res_dict[key].endswith('scan'):
            scan_folder, scan = os.path.split(res_dict[key])
            strg = scan[:-5] + '.strg'
            scan_folders.add(scan_folder)
            strg_names.add(strg)
    for folder in strg_folders:
        for strg in strg_names:
            new_path = f'{folder}/{strg}'
            if 'Scans_Chozo_Lore/0a eyes' not in new_path: # avoid one annoying false positive
                match_result = update_if_matched(new_path, 'strg!!', res_dict, commit)
                if match_result.value == 1 and commit:
                    matched += 1
    for folder in scan_folders:
        for scan in scan_names:
            new_path = f'{folder}/{scan}'
            match_result = update_if_matched(new_path, 'scan!!', res_dict, commit)
            if match_result.value == 1 and commit:
                matched += 1

    return matched
