name: Update Badges

on:
  push:
    branches:
      - main
    paths:
      - 'database/mp_resources.db'
  workflow_dispatch:
jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.13

      - name: Check sqlite3 version (pre-upgrade)
        run: sqlite3 --version

      # The ubuntu-latest runner for GitHub Actions (currently 24.04) uses an older
      # version of sqlite3. For more details, see:
      # <https://github.com/actions/runner-images/issues/9033#issuecomment-1857780470>
      - name: Upgrade sqlite3
        run: |
          download_link="https://www.sqlite.org/2025/sqlite-tools-linux-x64-3500000.zip"
          wget "$download_link" -P /tmp
          unzip "/tmp/$(basename "$download_link")" -d /tmp
          sudo install /tmp/sqlite3 /usr/local/bin/
      - name: Check sqlite3 version (post-upgrade)
        run: sqlite3 --version

      - name: Generate stats
        run:  python utils/generate_readme_stats.py

      - name: MP1 Badge
        uses: Schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BADGE_GIST_TOKEN }}
          gistID: ee95a1c1692c93f03ccf1fc684583c7a
          filename: mp1_progress.json
          label: MP1
          message: ${{ env.MP1_MATCHED_PCT }}
          valColorRange: ${{ env.MP1_MATCHED_PCT }}
          maxColorRange: 100
          minColorRange: 0

      - name: MP2 Badge
        uses: Schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BADGE_GIST_TOKEN }}
          gistID: ee95a1c1692c93f03ccf1fc684583c7a
          filename: mp2_progress.json
          label: MP2
          message: ${{ env.MP2_MATCHED_PCT }}
          valColorRange: ${{ env.MP2_MATCHED_PCT }}
          maxColorRange: 100
          minColorRange: 0

      - name: All Badge
        uses: Schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BADGE_GIST_TOKEN }}
          gistID: ee95a1c1692c93f03ccf1fc684583c7a
          filename: all_progress.json
          label: All hashes
          message: ${{ env.ALL_MATCHED_PCT }}
          valColorRange: ${{ env.ALL_MATCHED_PCT }}
          maxColorRange: 100
          minColorRange: 0